server:
  port: 8083
  tomcat:
    max-threads: 1000
    min-spare-threads: 500
token:
  client_id: 96f0a816bfa0bf266e06
  client_secret: e41f87cef4fd75708c7ddbd2302c5eced3cca96e
  redirect_uri: http://localhost:8080/callback
spring:
  mail:
    host: smtp.qq.com
    password: gkdrfvzpwykzbgbc
    default-encoding: utf-8
    username: 408395920@qq.com
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    host: 192.168.161.129
    username: root
    password: root
    virtual-host: mj
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
    template:
      #重试参数
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
    #发送确认
    publisher-confirms: true
    publisher-returns: true
  data:
    elasticsearch:
      cluster-name: xxp-cluster
      cluster-nodes: 192.168.161.129:9301
  redis:
    host: 192.168.161.129
    jedis:
      pool:
        max-active: 10
        max-idle: 10
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.161.129:3306/majiang?characterEncoding=UTF8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#logging:
#  file:
#    max-size: 2MB
#  level:
#    root: info
#    com:
#      xu:
#        majiangcommunity:
#          dao: info
#  path: F:\log\
mj:
  upload:
    agreeTypes:
      - image/jpeg
      - image/png
      - image/bmp
minio:
  endpoint: http://192.168.161.129:9090 #MinIO服务所在地址
  bucketName: image #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
